### ISSUE TITLE
1.12.2 Elytra unsupported?

### ISSUE THREAD

**Issue by H-QueerCoded** [quat1024/AutoThirdPerson#14]
Was wondering what the reason is that Elytra support is forcibly disabled in 1.12.2
https://github.com/quat1024/AutoThirdPerson/blob/7312ddb4588bedba8045266b35b3d69d7c87b3a4/Forge-1.12.2/src/main/java/agency/highlysuspect/autothirdperson/forge/OneTwelveTwoAutoThirdPerson.java#L131-L133

**Comment by quat1024** [comment]
...I think, in a total stroke of genius, I forgot elytra were in 1.12

**Comment by quat1024** [comment]
Fixed in 2.2-forge-1.12.2
