### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by nco2k** [quat1024/AutoThirdPerson#15]
any plans for 1.20.4?

**Comment by quat1024** [comment]
Any work i put in to 1.20.4 will become wasted work when mojang pushes the 1.20.5 theyve been teasing for six decades now. I do not play Mojang's games anymore

**Comment by nco2k** [comment]
its a shame that such a great mod is basically dead now. i understand your frustration though. microsoft is making things very difficult for everyone.

**Comment by icynstant** [comment]
1.20.6/1.20.5 pls

**Comment by quat1024** [comment]
Why should i port to a dead version like 1.20.5, especially when 1.21 is coming this weekend or next
