### ISSUE TITLE
Compatibility with Leawind's Third Person

### ISSUE THREAD

**Issue by polykatt** [quat1024/AutoThirdPerson#19]
This seems to be incompatible with [Leawind's Third Person](https://www.curseforge.com/minecraft/mc-mods/leawind-third-person). Would it be possible to have these mods work together?

**Comment by Leawind** [comment]
I've fixed this in https://github.com/Leawind/Third-Person/commit/9d55a97f4df77dc6b4b4bf078638f40dbe71f015
You will see it in next version of LTP

**Comment by polykatt** [comment]
Oh great thanks! Great mod btw, definitely my favorite third person mod ^-^

**Comment by Adidiii** [comment]
Close this issue if it's completed & fixed
