### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DTX3** [quat1024/AutoThirdPerson#22]
I've just installed this and it doesn't seem to do anything. It's not automatically switching to third person when I get into boats, swim etc..?

Could it be a mod conflict?

[latest.log](https://github.com/user-attachments/files/18231088/latest.log)

Version: auto_third_person-fabric-1.20.1-2.1

**Comment by DTX3** [comment]
Actually I found which mod its clashing with. Nimble https://modrinth.com/mod/nimble

**Comment by quat1024** [comment]
All Auto Third Person does is press f5 for you (by setting the same game setting that pressing f5 does); if it doesn't work with other mods I'd think that's on them
