### ISSUE TITLE
1.19 update?

### ISSUE THREAD

**Issue by haugsvar** [quat1024/AutoThirdPerson#5]
An update to 1.19 would be very much appreciated.

**Comment by chimericdream** [comment]
If @quat1024 hasn't already started working on the update, I'd be willing to take a stab at updating the mod and submitting a pull request.

**Comment by quat1024** [comment]
It's not gonna be hard, i want to get rid of that stupid dependency though lol

Working on some toolchain stuff so hopefully updating mods will not be a miserable experience of waiting on gradle

**Comment by quat1024** [comment]
Update: Haha yeah, so it was a miserable experience of waiting on gradle.

1.19.2 fabrique here https://www.curseforge.com/minecraft/mc-mods/auto-third-person/files/3922616 and also oops there's a forge version now https://www.curseforge.com/minecraft/mc-mods/auto-third-person/files/3922618 not sure how that happened

(U will probably need to wait on curse to approve the files  or go on modrinth https://modrinth.com/mod/auto-third-person/versions )
