### ISSUE TITLE
Compatibility with Shoulder Surfing.

### ISSUE THREAD

**Issue by dehen** [quat1024/AutoThirdPerson#6]
I adore this mod, I just wished it had compatibility with Shoulder Surfing Reloaded for Fabric [[git](https://github.com/Exopandora/ShoulderSurfing)].

Even with Shoulder Surfing having "Replace Default Perspective" ticked, AutoThirdPerson still targets the default 3rd person perspective, instead of the shoulder cam. This is a bummer, because I'd like having a shouldercam autotrigger as I swim.

I didn't know which issue tracker this would belong to, so I [posted it](https://github.com/Exopandora/ShoulderSurfing/issues/95) to both.

**Comment by quat1024** [comment]
It looks like every time anyone calls `Options#setCameraType`, which is a side effect of pressing F5 but also [how this mod manages the perspective](https://github.com/quat1024/AutoThirdPerson/blob/f3dfa08c68cffbd2ba18f63fe5540486385db6e7/Xplat/src/main/java/agency/highlysuspect/autothirdperson/AutoThirdPerson.java#L147), Shoulder Surfing [disables itself](https://github.com/Exopandora/ShoulderSurfing/blob/master/common/src/main/java/com/teamderpy/shouldersurfing/mixins/MixinOptions.java). I don't really know why it does this, but I'm not very familiar with how this mod is configured

**Comment by dehen** [comment]
Closing as it looks like SSR has done [a fix](https://github.com/Exopandora/ShoulderSurfing/commit/e80d7d31678f96dc4a4089eda054beec8f63a63a) in the dev version. Thank you both!
